const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let feed={items:[]}, filter='current';
const favs=new Set(JSON.parse(localStorage.getItem('mansionFavorites')||'[]'));
const lastPrices=JSON.parse(localStorage.getItem('mansionLastPrices')||'{}');
const fmtPrice=v=>v==null?'—':`${Math.round(v/10000).toLocaleString()}万円`;
const fmtDate=s=>{try{return new Date(s).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'});}catch{return s||''}};

function priceDelta(x){const h=x.price_history||[]; if(h.length<2)return null; const a=h[h.length-2].price_yen,b=h[h.length-1].price_yen; return {delta:b-a,old:a,new:b};}
function sparkline(h){ if(!h||h.length<2)return ''; const vals=h.map(x=>x.price_yen/10000), min=Math.min(...vals), max=Math.max(...vals), span=Math.max(1,max-min); const pts=vals.map((v,i)=>`${i*100/(vals.length-1)},${62-(v-min)*52/span}`).join(' '); return `<svg class="spark" viewBox="0 0 100 70" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke"/><line x1="0" y1="64" x2="100" y2="64" stroke="#e5e7eb" stroke-width="1"/></svg>`; }
function changeBadge(x){const d=priceDelta(x); if(!d)return ''; const man=Math.round(Math.abs(d.delta)/10000); return d.delta<0?`<span class="badge down">↓ ${man}万降价</span>`:`<span class="badge up">↑ ${man}万涨价</span>`;}
function historyHtml(x){const h=x.price_history||[]; if(!h.length)return '<div class="history-row">还没有价格历史。</div>'; return h.slice().reverse().map((p,i)=>`<div class="history-row">${fmtDate(p.at)}　${fmtPrice(p.price_yen)}${i===0?' ← 当前':''}</div>`).join('')+sparkline(h);}
function card(x){const l=x.listing||{}, fav=favs.has(x.id), ppm=l.price_per_m2?`${(l.price_per_m2/10000).toFixed(1)}万円/㎡`:''; return `<article class="card" data-id="${x.id}"><div class="top"><div class="title">${esc(l.title||'未命名房源')}<div class="sub source">${esc(l.source||'')}</div></div><button class="fav ${fav?'on':''}" data-fav="${x.id}" aria-label="关注">${fav?'♥':'♡'}</button></div><div><span class="price">${fmtPrice(l.price_yen)}</span><span class="ppm">${ppm}</span></div><div class="meta">${l.category==='danchi'?'<span class="badge danchi">団地・电梯确认</span>':''}${changeBadge(x)}${l.layout?`<span class="badge">${esc(l.layout)}</span>`:''}${l.area_m2?`<span class="badge">${l.area_m2}㎡</span>`:''}${l.walk_minutes!=null?`<span class="badge">徒歩${l.walk_minutes}分</span>`:''}${l.build_year?`<span class="badge">${l.build_year}年築</span>`:''}${!x.current_match?'<span class="badge">不在当前筛选结果</span>':''}</div><div class="actions"><a class="btn" href="${escAttr(l.url)}" target="_blank" rel="noopener">打开原网站</a><button class="btn secondary" data-history="${x.id}">价格历史</button></div><div class="history" id="h-${x.id}">${historyHtml(x)}</div></article>`;}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));} function escAttr(s){return esc(s||'');}
function sorted(items){const v=$('#sort').value; return items.sort((a,b)=>{const A=a.listing||{},B=b.listing||{}; if(v==='price')return (A.price_yen??1e18)-(B.price_yen??1e18); if(v==='ppm')return (A.price_per_m2??1e18)-(B.price_per_m2??1e18); if(v==='walk')return (A.walk_minutes??999)-(B.walk_minutes??999); return String(b.last_seen||'').localeCompare(String(a.last_seen||''));});}
function render(){let items=[...(feed.items||[])]; if(filter==='current')items=items.filter(x=>x.current_match); if(filter==='fav')items=items.filter(x=>favs.has(x.id)); if(filter==='danchi')items=items.filter(x=>(x.listing||{}).category==='danchi'&&x.current_match); if(filter==='down')items=items.filter(x=>{const d=priceDelta(x);return d&&d.delta<0}); items=sorted(items); $('#list').innerHTML=items.map(card).join(''); $('#empty').style.display=items.length?'none':'block'; $('#nCurrent').textContent=(feed.items||[]).filter(x=>x.current_match).length; $('#nFav').textContent=favs.size; $('#nDown').textContent=(feed.items||[]).filter(x=>{const d=priceDelta(x);return d&&d.delta<0}).length; bind();}
function bind(){ $$('[data-fav]').forEach(b=>b.onclick=()=>{const id=b.dataset.fav; if(favs.has(id))favs.delete(id);else favs.add(id); localStorage.setItem('mansionFavorites',JSON.stringify([...favs])); render();}); $$('[data-history]').forEach(b=>b.onclick=()=>$('#h-'+b.dataset.history).classList.toggle('show')); }
$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render();}); $('#sort').onchange=render;
async function load(){try{const r=await fetch('data.json?ts='+Date.now(),{cache:'no-store'}); feed=await r.json(); $('#updated').textContent=`最近更新：${fmtDate(feed.updated_at)} · SUUMO / HOME'S / at home / Yahoo! / 三井 / 東急 / ノムコム / レンズ`; if(feed.failures?.length){$('#notice').classList.add('show');$('#notice').textContent='部分网站本次读取失败：'+feed.failures.join(' / ');} detectFavoriteChanges(); render();}catch(e){$('#updated').textContent='无法读取最新数据；请检查 GitHub Pages / data.json。';$('#notice').classList.add('show');$('#notice').textContent=String(e);}}
function detectFavoriteChanges(){let changed=[]; for(const x of feed.items||[]){if(!favs.has(x.id))continue; const p=(x.listing||{}).price_yen; if(p!=null&&lastPrices[x.id]!=null&&lastPrices[x.id]!==p)changed.push(`${(x.listing||{}).title}: ${fmtPrice(lastPrices[x.id])} → ${fmtPrice(p)}`); if(p!=null)lastPrices[x.id]=p;} localStorage.setItem('mansionLastPrices',JSON.stringify(lastPrices)); if(changed.length){$('#notice').classList.add('show');$('#notice').textContent='你关注的房源价格有变化：'+changed.join('；'); if('Notification'in window&&Notification.permission==='granted') new Notification('关注房源价格变化',{body:changed[0]});}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js'); if('Notification'in window&&Notification.permission==='default'){document.addEventListener('click',()=>Notification.requestPermission(),{once:true});}
load();
